import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";

import {
  MatButtonModule,
  MatDatepickerModule,
  MatListModule,
  MatIconModule,
  MatCardModule,
  MatMenuModule,
  MatInputModule,
  MatButtonToggleModule,
  MatProgressSpinnerModule,
  MatSelectModule,
  MatSlideToggleModule,
  MatDialogModule,
  MatSnackBarModule,
  MatToolbarModule,
  MatTabsModule,
  MatSidenavModule,
  MatTooltipModule,
  MatCheckboxModule,
  MatRadioModule,
  MatGridListModule,
  MatProgressBarModule,
  MatSliderModule,
  MatChipsModule,
  MatRippleModule,
  MatExpansionModule,
  MatTableModule,
  MatDividerModule,
  MatStepperModule,
  MatNativeDateModule,
} from "@angular/material";

import { CovalentLoadingModule, CovalentDialogsModule } from '@covalent/core';

import { ScrollDispatchModule } from "@angular/cdk/scrolling";

import { FlexLayoutModule } from "@angular/flex-layout";

import { CreditCardDirectivesModule } from 'angular-cc-library';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    FlexLayoutModule,
    FormsModule,
    MatButtonModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatListModule,
    MatIconModule,
    MatCardModule,
    MatMenuModule,
    MatInputModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatTabsModule,
    MatSidenavModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatRadioModule,
    MatProgressBarModule,
    MatSliderModule,
    MatChipsModule,
    MatGridListModule,
    MatRippleModule,
    MatExpansionModule,
    MatTableModule,
    ScrollDispatchModule,
    MatExpansionModule,
    MatDividerModule,
    MatStepperModule,
    CovalentLoadingModule,
    CovalentDialogsModule,
    CreditCardDirectivesModule
  ],
  exports: [
    CommonModule,
    FlexLayoutModule,
    FormsModule,
    MatButtonModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatListModule,
    MatIconModule,
    MatCardModule,
    MatMenuModule,
    MatInputModule,
    MatButtonToggleModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatSlideToggleModule,
    MatDialogModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatTabsModule,
    MatSidenavModule,
    MatTooltipModule,
    MatCheckboxModule,
    MatRadioModule,
    MatProgressBarModule,
    MatSliderModule,
    MatChipsModule,
    MatGridListModule,
    MatRippleModule,
    MatExpansionModule,
    MatTableModule,
    ScrollDispatchModule,
    MatDividerModule,
    MatStepperModule,
    CovalentLoadingModule,
    CovalentDialogsModule,
    CreditCardDirectivesModule
  ]
})
export class SharedModule {}
